spring.application.name=backend

# Database (Aiven Cloud MySQL)
spring.datasource.url=jdbc:mysql://mysql-1cf7086a-career-path.i.aivencloud.com:17479/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1V4VS-lwO_28vLxDcef

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080